---
title: "R Notebook"
output: html_notebook
---

# Load libraries
```{r}
library(tidyverse)
```


# Read in data
```{r}
gm <- read_csv("gapminder.csv")
```

# verb functionalites
```{r}


#Create dataset with missing values
dat <- as_tibble_col(x = c(1, 2, 3, NA, NA, NA, 5, 7, 8), column_name = "var")

#filter to NAs
filter(dat, var == NA)  # <- doesn't work
filter(dat, is.na(var)) # <-  works
filter(dat, !is.na(var))


#Select multiple columns
select(gm, year:pop)
select(gm, starts_with("gdp"))
select(gm, ends_with("Percap"))
select(gm, contains("erc"))

```



# Working with pipes
```{r}


gm2 <- gm %>% 
  filter(year > 1960) %>% 
  select(continent, country, everything()) %>% 
  mutate(lifeExp_10 = lifeExp * 10 ) %>% 
  arrange(desc(lifeExp_10)) 


```

# Some more ggplot
```{r}

ggplot(gm, aes(x = log10(gdpPercap), y = lifeExp, color = continent)) +
  geom_point(show.legend = FALSE) +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "YAY! TITLE!", x = "WOO X-AXIS!", y = "Y-AXIS, you kidding me?!") +
  facet_wrap(~continent)
  
  


```



# Using pwr


## Load libraries
```{r}
#install.packages("pwr")
library(pwr)
```


## a-priori t-tets
```{r}
pwr.t.test(
  n = NULL, 
  d = .12, 
  sig.level = .05, 
  power = .80, 
  type = "two.sample", 
  alternative = "two.sided"
  )
```

##a-priori ANOVA
```{r}
pwr.anova.test(
  k = 3,
  n = NULL,
  f = .15,
  sig.level = .05,
  power = .80
  )
```


## Post hoc t-test
```{r}
pwr.t.test(
  n = 200, 
  d = .25, 
  sig.level = .01, 
  power = NULL, 
  type = "two.sample", 
  alternative = "two.sided"
  )
```

## Post-hoc ANOVA
```{r}
pwr.anova.test(
  k = 5,
  n = 50,
  f = .10,
  sig.level = .05,
  power = NULL
  )
```
